name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Known hosts & test login
        env:
          HOST: ${{ secrets.VPS_SSH_HOST }}
          USER: ${{ secrets.VPS_SSH_USERNAME }}
          PORT: ${{ secrets.VPS_SSH_PORT }}
        run: |
          set -e
          mkdir -p ~/.ssh
          ssh-keyscan -p "${PORT:-22}" "$HOST" >> ~/.ssh/known_hosts
          ssh -vvv -p "${PORT:-22}" "$USER@$HOST" "echo 'GHA SSH OK'; uname -a"

      - name: SSH and Deploy (appleboy)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          port: ${{ secrets.VPS_SSH_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          debug: true
          timeout: 60s
          command_timeout: 5m
          script_stop: true
          script: |
            set -euo pipefail
            cd ~/badminton-backend-git
            git fetch --all
            git reset --hard origin/main
            npm ci --only=production || npm install --only=production
            pm2 describe badminton-tournament-backend >/dev/null 2>&1 \
              && pm2 reload badminton-tournament-backend \
              || pm2 start server.js --name badminton-tournament-backend
            pm2 save
